apiVersion: v1
kind: LimitRange
metadata:
  name: orion-container-defaults
  namespace: chapter-02-lab
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 25m
        memory: 32Mi
      default:
        cpu: 100m
        memory: 64Mi
