apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: dev
            cluster: eks-dev
          - environment: uat
            cluster: eks-uat
          - environment: prod
            cluster: eks-prod
  template:
    metadata:
      name: metrics-server-{{environment}}
      labels:
        app.kubernetes.io/part-of: platform
        app.kubernetes.io/component: metrics-server
        environment: '{{environment}}'
    spec:
      project: default
      source:
        repoURL: https://kubernetes-sigs.github.io/metrics-server/
        chart: metrics-server
        targetRevision: 3.13.1
        helm:
          releaseName: metrics-server
          values: |
            replicas: 2
      destination:
        name: '{{cluster}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
